### ISSUE TITLE
Stopped working with ESPHome 2026.2.0

### ISSUE THREAD

**Issue by DarkFeniXZp** [myhomeiot/esphome-components#46]
Don't compile with ESPHome 2026.2.0
`src/esphome/components/myhomeiot_ble_host/myhomeiot_ble_host.cpp: In member function 'virtual void esphome::myhomeiot_ble_host::MyHomeIOT_BLEHost::loop()':
src/esphome/components/myhomeiot_ble_host/myhomeiot_ble_host.cpp:37:13: error: 'esphome::esp32_ble_tracker::ClientState esphome::esp32_ble_tracker::ESPBTClient::state_' is private within this context
   37 |   if (this->state_ == esp32_ble_tracker::ClientState::INIT)
      |             ^~~~~~
In file included from src/esphome/components/myhomeiot_ble_host/myhomeiot_ble_host.h:6,
                 from src/esphome/components/myhomeiot_ble_host/myhomeiot_ble_host.cpp:5:
src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.h:279:15: note: declared private here
  279 |   ClientState state_{ClientState::INIT};
      |               ^~~~~~
src/esphome/components/myhomeiot_ble_host/myhomeiot_ble_host.cpp:37:13: note: field 'esphome::esp32_ble_tracker::ClientState esphome::esp32_ble_tracker::ESPBTClient::state_' can be accessed via 'esphome::esp32_ble_tracker::ClientState esphome::esp32_ble_tracker::ESPBTClient::state() const'
   37 |   if (this->state_ == esp32_ble_tracker::ClientState::INIT)
      |             ^~~~~~
      |             state()
*** [.pioenvs/bletracker/src/esphome/components/myhomeiot_ble_host/myhomeiot_ble_host.cpp.o] Error 1`

**Comment by ckd77** [comment]
I think so too. Modifying this line in myhomeiot_ble_host.cpp from if (this->state_ == esp32_ble_tracker::ClientState::INIT) to if (this->state() == esp32_ble_tracker::ClientState::INIT) should fix it.

**Comment by myhomeiot** [comment]
Hello, @ckd77 right, please modify line 37 of `myhomeiot_ble_host.cpp` (state_ -> state()) and let's me know if component will work as expected. I don't have access to test environment right now, so I can't test it to be sure if it's keeps working correctly with this change. Thanks in advance.

From
```
  if (this->state_ == esp32_ble_tracker::ClientState::INIT)
```

to
```
  if (this->state() == esp32_ble_tracker::ClientState::INIT)
```

**Comment by ckd77** [comment]
What I got working on my home assistant was setting up myhomeiot_ble_client and myhomeiot_ble_host locally. You can make my correction without any problem ;)

**Comment by myhomeiot** [comment]
Fixed in [1.0.14](https://github.com/myhomeiot/esphome-components/releases/tag/1.0.14)
